apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sample-api
  description: This is a sample API
  tags:
    - sample
    - api
spec:
  type: openapi
  lifecycle: experimental
  owner: junickmarco
  definition: |
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths:
      /:
        get:
          summary: Sample endpoint
          responses:
            '200':
              description: Successful response
